### ISSUE TITLE
Cannot create developer user

### ISSUE THREAD

**Issue by MetHeinen** [e-ucm/rage-analytics#10] opened 2015-11-17 07:16 UTC
[report-2015_11_17_07_40.txt](https://github.com/e-ucm/rage-analytics/files/36369/report-2015_11_17_07_40.txt)
After installing RAGE-Analaytics it is not possible to create user accounts, even not a dev account to set up new games.
See attachement for more information about the system.

**Comment by manuel-freire** [comment] 2015-11-17 10:24
When you write that it is not possible -  could you specify what you see? This is the a2 portion of your report:

```
[service]--------------------------------------
5b7bdc48c68f        eucm/a2                        "npm run docker-start"   10 minutes ago      Up 10 minutes       0.0.0.0:3000->3000/tcp   opt_a2_1
[stats]--------------------------------------
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O               BLOCK I/O
5b7bdc48c68f        0.00%               143 MB / 6.252 GB   2.29%               47.58 kB / 52.94 kB   50.91 MB / 16.38 kB
[logs]--------------------------------------

(... snip ...)
Mongo db Connected!
Mongoose: users.ensureIndex({ email: 1 }) { unique: true, background: true }  
Mongoose: applications.ensureIndex({ prefix: 1 }) { unique: true, background: true }  
Mongoose: users.ensureIndex({ username: 1 }) { unique: true, background: true }  
Mongoose: applications.ensureIndex({ host: 1 }) { unique: true, background: true }  
Mongoose: users.ensureIndex({ username: 1 }) { unique: true, background: true }  
Mongoose: users.ensureIndex({ email: 1 }) { unique: true, background: true }  
Mongoose: applications.ensureIndex({ prefix: 1 }) { unique: true, background: true }  
Mongoose: users.findOne({ '$or': [ { username: 'root' } ] }) { fields: {} }  
POST /api/login 200 4786.420 ms - 313
-DEBUG-ACL: Requesting post on /api/applications by user root
-DEBUG-ACL: Allowed post on /api/applications by user root
Mongoose: applications.findOne({ prefix: 'gleaner' }) { fields: undefined }  
Mongoose: applications.insert({ name: 'Rage Analytics Backend', prefix: 'gleaner', host: 'http://172.17.0.12:3300/api', owner: 'root', _id: ObjectId("564ac9ee2d17d342001b2982"), timeCreated: new Date("Tue, 17 Nov 2015 06:32:14 GMT"), autoroles: [ 'student', 'teacher', 'developer' ], routes: [ 'gleaner/games/public', 'gleaner/games/:gameId/versions', 'gleaner/games/:gameId/versions/:versionId', 'gleaner/games/:gameId/versions/:versionId/sessions/my', 'gleaner/sessions/:sessionId/results', 'gleaner/sessions/:sessionId', 'gleaner/sessions/:sessionId/remove', 'gleaner/sessions/:sessionId/results/:resultsId', 'gleaner/games/:gameId/versions/:versionId/sessions', 'gleaner/sessions/:sessionId/event/:event', 'gleaner/games/my', 'gleaner/games/:gameId', 'gleaner/games' ], anonymous: [ '/games/:id/:versionId', '/collector/start/:trackingCode', '/collector/track' ], __v: 0 })   
POST /api/applications 200 995.636 ms - 798
[service]--------------------------------------
```

I would expect something similar to mine:

```
[service]--------------------------------------
366739fcb6b7        eucm/a2                        "npm run docker-start"   3 minutes ago       Up 3 minutes        0.0.0.0:3000->3000/tcp   rageanalytics_a2_1
[stats]--------------------------------------
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O
366739fcb6b7        0.00%               116.2 MB / 8.309 GB   1.40%               69.45 kB / 70.04 kB   7.881 MB / 8.192 kB
[logs]--------------------------------------

(... snip ...)
Mongo db Connected!
Mongoose: users.ensureIndex({ email: 1 }) { unique: true, background: true }  
Mongoose: applications.ensureIndex({ prefix: 1 }) { unique: true, background: true }  
Mongoose: users.ensureIndex({ username: 1 }) { unique: true, background: true }  
Mongoose: users.ensureIndex({ username: 1 }) { unique: true, background: true }  
Mongoose: applications.ensureIndex({ host: 1 }) { unique: true, background: true }  
Mongoose: users.ensureIndex({ email: 1 }) { unique: true, background: true }  
Mongoose: applications.ensureIndex({ prefix: 1 }) { unique: true, background: true }  
Mongoose: users.findOne({ '$or': [ { username: 'root' } ] }) { fields: {} }  
POST /api/login 200 574.533 ms - 313
-DEBUG-ACL: Requesting post on /api/applications by user root
-DEBUG-ACL: Allowed post on /api/applications by user root
Mongoose: applications.findOne({ prefix: 'gleaner' }) { fields: undefined }  
Mongoose: applications.insert({ name: 'Rage Analytics Backend', prefix: 'gleaner', host: 'http://172.17.0.12:3300/api', owner: 'root', _id: ObjectId("564afd54fa148a4200d6987d"), timeCreated: new Date("Tue, 17 Nov 2015 10:11:32 GMT"), autoroles: [ 'student', 'teacher', 'developer' ], routes: [ 'gleaner/games/public', 'gleaner/games/:gameId/versions', 'gleaner/games/:gameId/versions/:versionId', 'gleaner/games/:gameId/versions/:versionId/sessions/my', 'gleaner/sessions/:sessionId/results', 'gleaner/sessions/:sessionId', 'gleaner/sessions/:sessionId/remove', 'gleaner/sessions/:sessionId/results/:resultsId', 'gleaner/games/:gameId/versions/:versionId/sessions', 'gleaner/sessions/:sessionId/event/:event', 'gleaner/games/my', 'gleaner/games/:gameId', 'gleaner/games' ], anonymous: [ '/games/:id/:versionId', '/collector/start/:trackingCode', '/collector/track' ], __v: 0 })   
POST /api/applications 200 104.130 ms - 798
Mongoose: applications.findOne({ prefix: 'gleaner' }) { fields: undefined }  
GET /api/proxy/gleaner/games/public 401 8.875 ms - 46
Mongoose: applications.findOne({ prefix: 'gleaner' }) { fields: undefined }  
GET /api/proxy/gleaner/games/public 401 6.015 ms - 46
OPTIONS /api/signup 200 1.101 ms - 2
Mongoose: applications.findOne({ prefix: 'gleaner' }) { fields: undefined }  
Mongoose: users.findOne({ '$or': [ { username: 'test' } ] }) { fields: { hash: 0, salt: 0 } }  
Mongoose: users.insert({ salt: '24b45338fd180e8b5187c75e2c4446cd7c88786fc8bb754ee989178c0c13a215', hash: '4b10c562cec5d24ec9ff3320f3e022f8b72206f76bf0b50d16044511fba58c59c09e5161d9101da5b6f06c52b3b59e9a8e8896a156f570a98f0bf2ad3390864ea0282c17163e171214a7fb3006c2b4439a318019e19d7c1fd9843916ecebe45d806bd04711a3a51c9a4abce7d71ec29e9b8a5267d8652e443ca92d4153ff3fc90192179946610e06d45b7a5cda4e6cd86cf29e8a7d99d797e6937653df44c6c2979bcc7480badb5db201b73528f9c9aef73510c098f8c642e5eb94755b24054cc9735af6cad01a95d80fd466152329d53e6f1fbe5fd82948fe6c6f103432a925a4caff50690b256f5817e14088f2da825857cde4ba1a11d0a751a350bb816947d687c6d2b560fe099dafa49abb100a9c01b34f02b76ebb4b27352d287d99d0e33d61085a31b03e788cd89886edfbb63ae383dda4d8af7781dd218bf2f2c669da79a29e34134bd4cee8dbbb91837a45948f739ceb2c9da3440c17515ee19a6392c3f50d5b7b52e921ff0df2ac31206b4f67057dce2e2baf60289b32c233d8fe9bea22e707ce70db903261df315e09542285759f5ec4de2f18b798eeb9e6638c2c18997285765c67be2b22950e13a542e83c735c65652348452aff3a64268b850684623a3dcbb3e07d9c484846a9326137ce0a009a73c737b9f7aa4c31a5cfde9417701130453247e6890c47fecde8bd62987c9790c5b0ddddc600a8f2055479c4', username: 'test', email: 'test@test.test', _id: ObjectId("564afde7fa148a4200d6987e"), timeCreated: new Date("Tue, 17 Nov 2015 10:13:59 GMT"), verification: { complete: false }, name: { last: '', middle: '', first: '' }, __v: 0 })   
POST /api/signup 200 1071.769 ms - 86
sending welcome email failed: Email failed to send. Error: connection encountered an error
Mongoose: applications.findOne({ prefix: 'gleaner' }) { fields: undefined }  
GET /api/proxy/gleaner/games/public 401 8.395 ms - 46
OPTIONS /api/login 200 1.030 ms - 2
Mongoose: users.findOne({ '$or': [ { username: 'test' } ] }) { fields: {} }  
POST /api/login 200 531.166 ms - 313
OPTIONS /api/users/564afde7fa148a4200d6987e/roles 200 0.316 ms - 2
Mongoose: users.findOne({ _id: ObjectId("564afde7fa148a4200d6987e") }) { fields: { hash: 0, salt: 0 } }  
GET /api/users/564afde7fa148a4200d6987e/roles 200 16.956 ms - 13
OPTIONS /api/proxy/gleaner/games/my 200 0.218 ms - 2
OPTIONS /api/proxy/gleaner/games/my 200 0.176 ms - 2
OPTIONS /api/proxy/gleaner/games/my 200 0.331 ms - 2
Mongoose: applications.findOne({ prefix: 'gleaner' }) { fields: undefined }  
Mongoose: applications.findOne({ prefix: 'gleaner' }) { fields: undefined }  
-DEBUG-ACL: Allowed get on gleaner/games/my by user test
-DEBUG-ACL: Allowed get on gleaner/games/my by user test
GET /api/proxy/gleaner/games/my 200 47.754 ms - 2
Mongoose: applications.findOne({ prefix: 'gleaner' }) { fields: undefined }  
GET /api/proxy/gleaner/games/my 200 54.988 ms - 2
-DEBUG-ACL: Allowed get on gleaner/games/my by user test
GET /api/proxy/gleaner/games/my 304 14.962 ms - -
```

**Comment by manuel-freire** [comment] 2015-11-17 10:54
This seems to be caused by your network requirements, to summarize:
- only one IP address will be accessible, that of the "rage analytics server"
- all requests must be to this IP address, without accessing any internal IP addresses directly. 

I understand that this is intended for VM-like, isolated deployments. It is definitely something that we want to support - I will leave this issue open until we do so.

**Comment by manuel-freire** [comment] 2015-11-26 11:04
The issue was due to internal IPs being exposed to external clients (your web-browser). This has been solved in the front-end, and should no longer be the case. Marking as closed.

**Closed as completed by manuel-freire** 2015-11-26 11:04 UTC

**Comment by sgcitinnov** [comment] 2016-05-04 13:35
Hello Manuel-Freire,

I downloaded and installed Rage-Analytics yesterday and may be experiencing a similar problem. The RAGE services appear to be up and I can access the front-end UIs just fine, initially. However the API calls being used by the front-end javascript to create new users in the sign-up page fail:

> HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
> (XHR): POST - http://192.9.206.134:3350/api/signup

I really want to access the RAGE platform from my host machine, rather than have to do so within Docker. Is there a solution?

Kind regards,
Simon
[report-2016_05_04_14_18.txt](https://github.com/e-ucm/rage-analytics/files/248807/report-2016_05_04_14_18.txt)

**Comment by manuel-freire** [comment] 2016-05-05 16:36
I can't really find any errors in your logs (beyond the 404 in /api/signup). However, I suspect that trying to connect to <ip>:3350 is causing problems that would be avoided if using localhost:3350. Can you try this and confirm whether it works?
